### ISSUE TITLE
Unable to build on Python 3.12

### ISSUE THREAD

**Issue by robd003** [MagicStack/py-pgproto#24]
Getting a lot of these errors when trying to build https://github.com/MagicStack/asyncpg on Python 3.12:
```
  asyncpg/pgproto/pgproto.c:40800:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
  asyncpg/pgproto/pgproto.c:40855:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
  asyncpg/pgproto/pgproto.c:41034:55: error: no member named 'ob_digit' in 'struct _longobject'
              const digit* digits = ((PyLongObject*)x)->ob_digit;
                                    ~~~~~~~~~~~~~~~~~~  ^
```

I believe this can be solved by converting `((PyLongObject*)x)->ob_digit` to `((PyLongObject*)x)->long_value->ob_digit`

**Comment by robd003** [comment]
Checking to see if cython 3.0.4 fixes this
